title: Sadry Abu Seman # your name (or website title) here
logo: "/images/Profile-Picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am an assistant professor, software, web and mobile developer. Most of my research focuses on visual programming, 
  computer science pedagogy & learning analytics<br>
  <br>
  <a href="https://muhdsadry.github.io/online-cv">View My Online CV</a><br> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
