title: Sadry Abu Seman # your name (or website title) here
logo: "/images/Profile-Picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am an assistant professor, software engineer, web and mobile developer. My Research mostly focusing on visual programming, 
  learning analytics & computer science Pedagogy<br>
  <br>
  <a href="https://my.linkedin.com/in/sadry-abu-seman-93726b25">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
